package domain.util.resource

enum class Cause {
    API_ERROR,
    DATABASE_ERROR,
    ELEMENT_NOT_FOUND,
    INVALID_CREDENTIALS,
    INVALID_EMAIL,
    INVALID_PASSCODE,
    NETWORK_ERROR,
    PASSWORD_MISMATCH,
    PASSWORD_TOO_SHORT,
    PERMISSION_DENIED,
    REQUEST_TIMEOUT,
    USER_NOT_AUTHENTICATED,
    USER_NOT_FOUND,
    WRONG_PASSCODE,
    UNKNOWN;
}
